package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Accountpics generated by hbm2java
 */
public class Accountpics  implements java.io.Serializable {


     private Long autoId;
     private long userId;
     private String picId;
     private String deviceId;
     private String origName;
     private long editTstamp;
     private long timeStamp;
     private boolean accpic;
     private boolean deleted;
     private String pictype;
     private long picsize;
     private byte privacy;
     private byte download;
     private byte doLidislike;
     private byte seeLidislike;
     private byte doTalking;
     private byte seeTalking;
     private byte doComment;
     private byte seeComment;
     private byte doShare;
     private byte seeShare;
     private boolean likes;
     private boolean dislikes;
     private boolean talkings;
     private boolean comments;
     private boolean shares;
     private boolean talkingImage;
     private boolean talkingAudio;
     private boolean talkingVideo;
     private boolean talkingFile;
     private boolean talkingSticker;
     private boolean commentImage;
     private boolean commentAudio;
     private boolean commentVideo;
     private boolean commentFile;
     private boolean commentSticker;

    public Accountpics() {
    }

    public Accountpics(long userId, String picId, String deviceId, String origName, long editTstamp, long timeStamp, boolean accpic, boolean deleted, String pictype, long picsize, byte privacy, byte download, byte doLidislike, byte seeLidislike, byte doTalking, byte seeTalking, byte doComment, byte seeComment, byte doShare, byte seeShare, boolean likes, boolean dislikes, boolean talkings, boolean comments, boolean shares, boolean talkingImage, boolean talkingAudio, boolean talkingVideo, boolean talkingFile, boolean talkingSticker, boolean commentImage, boolean commentAudio, boolean commentVideo, boolean commentFile, boolean commentSticker) {
       this.userId = userId;
       this.picId = picId;
       this.deviceId = deviceId;
       this.origName = origName;
       this.editTstamp = editTstamp;
       this.timeStamp = timeStamp;
       this.accpic = accpic;
       this.deleted = deleted;
       this.pictype = pictype;
       this.picsize = picsize;
       this.privacy = privacy;
       this.download = download;
       this.doLidislike = doLidislike;
       this.seeLidislike = seeLidislike;
       this.doTalking = doTalking;
       this.seeTalking = seeTalking;
       this.doComment = doComment;
       this.seeComment = seeComment;
       this.doShare = doShare;
       this.seeShare = seeShare;
       this.likes = likes;
       this.dislikes = dislikes;
       this.talkings = talkings;
       this.comments = comments;
       this.shares = shares;
       this.talkingImage = talkingImage;
       this.talkingAudio = talkingAudio;
       this.talkingVideo = talkingVideo;
       this.talkingFile = talkingFile;
       this.talkingSticker = talkingSticker;
       this.commentImage = commentImage;
       this.commentAudio = commentAudio;
       this.commentVideo = commentVideo;
       this.commentFile = commentFile;
       this.commentSticker = commentSticker;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getPicId() {
        return this.picId;
    }
    
    public void setPicId(String picId) {
        this.picId = picId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public String getOrigName() {
        return this.origName;
    }
    
    public void setOrigName(String origName) {
        this.origName = origName;
    }
    public long getEditTstamp() {
        return this.editTstamp;
    }
    
    public void setEditTstamp(long editTstamp) {
        this.editTstamp = editTstamp;
    }
    public long getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(long timeStamp) {
        this.timeStamp = timeStamp;
    }
    public boolean isAccpic() {
        return this.accpic;
    }
    
    public void setAccpic(boolean accpic) {
        this.accpic = accpic;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public String getPictype() {
        return this.pictype;
    }
    
    public void setPictype(String pictype) {
        this.pictype = pictype;
    }
    public long getPicsize() {
        return this.picsize;
    }
    
    public void setPicsize(long picsize) {
        this.picsize = picsize;
    }
    public byte getPrivacy() {
        return this.privacy;
    }
    
    public void setPrivacy(byte privacy) {
        this.privacy = privacy;
    }
    public byte getDownload() {
        return this.download;
    }
    
    public void setDownload(byte download) {
        this.download = download;
    }
    public byte getDoLidislike() {
        return this.doLidislike;
    }
    
    public void setDoLidislike(byte doLidislike) {
        this.doLidislike = doLidislike;
    }
    public byte getSeeLidislike() {
        return this.seeLidislike;
    }
    
    public void setSeeLidislike(byte seeLidislike) {
        this.seeLidislike = seeLidislike;
    }
    public byte getDoTalking() {
        return this.doTalking;
    }
    
    public void setDoTalking(byte doTalking) {
        this.doTalking = doTalking;
    }
    public byte getSeeTalking() {
        return this.seeTalking;
    }
    
    public void setSeeTalking(byte seeTalking) {
        this.seeTalking = seeTalking;
    }
    public byte getDoComment() {
        return this.doComment;
    }
    
    public void setDoComment(byte doComment) {
        this.doComment = doComment;
    }
    public byte getSeeComment() {
        return this.seeComment;
    }
    
    public void setSeeComment(byte seeComment) {
        this.seeComment = seeComment;
    }
    public byte getDoShare() {
        return this.doShare;
    }
    
    public void setDoShare(byte doShare) {
        this.doShare = doShare;
    }
    public byte getSeeShare() {
        return this.seeShare;
    }
    
    public void setSeeShare(byte seeShare) {
        this.seeShare = seeShare;
    }
    public boolean isLikes() {
        return this.likes;
    }
    
    public void setLikes(boolean likes) {
        this.likes = likes;
    }
    public boolean isDislikes() {
        return this.dislikes;
    }
    
    public void setDislikes(boolean dislikes) {
        this.dislikes = dislikes;
    }
    public boolean isTalkings() {
        return this.talkings;
    }
    
    public void setTalkings(boolean talkings) {
        this.talkings = talkings;
    }
    public boolean isComments() {
        return this.comments;
    }
    
    public void setComments(boolean comments) {
        this.comments = comments;
    }
    public boolean isShares() {
        return this.shares;
    }
    
    public void setShares(boolean shares) {
        this.shares = shares;
    }
    public boolean isTalkingImage() {
        return this.talkingImage;
    }
    
    public void setTalkingImage(boolean talkingImage) {
        this.talkingImage = talkingImage;
    }
    public boolean isTalkingAudio() {
        return this.talkingAudio;
    }
    
    public void setTalkingAudio(boolean talkingAudio) {
        this.talkingAudio = talkingAudio;
    }
    public boolean isTalkingVideo() {
        return this.talkingVideo;
    }
    
    public void setTalkingVideo(boolean talkingVideo) {
        this.talkingVideo = talkingVideo;
    }
    public boolean isTalkingFile() {
        return this.talkingFile;
    }
    
    public void setTalkingFile(boolean talkingFile) {
        this.talkingFile = talkingFile;
    }
    public boolean isTalkingSticker() {
        return this.talkingSticker;
    }
    
    public void setTalkingSticker(boolean talkingSticker) {
        this.talkingSticker = talkingSticker;
    }
    public boolean isCommentImage() {
        return this.commentImage;
    }
    
    public void setCommentImage(boolean commentImage) {
        this.commentImage = commentImage;
    }
    public boolean isCommentAudio() {
        return this.commentAudio;
    }
    
    public void setCommentAudio(boolean commentAudio) {
        this.commentAudio = commentAudio;
    }
    public boolean isCommentVideo() {
        return this.commentVideo;
    }
    
    public void setCommentVideo(boolean commentVideo) {
        this.commentVideo = commentVideo;
    }
    public boolean isCommentFile() {
        return this.commentFile;
    }
    
    public void setCommentFile(boolean commentFile) {
        this.commentFile = commentFile;
    }
    public boolean isCommentSticker() {
        return this.commentSticker;
    }
    
    public void setCommentSticker(boolean commentSticker) {
        this.commentSticker = commentSticker;
    }




}


