package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Captchacode generated by hbm2java
 */
public class Captchacode  implements java.io.Serializable {


     private Long autoId;
     private String captchaId;
     private String captchaCode;
     private boolean isUsed;
     private long setTimestamp;

    public Captchacode() {
    }

    public Captchacode(String captchaId, String captchaCode, boolean isUsed, long setTimestamp) {
       this.captchaId = captchaId;
       this.captchaCode = captchaCode;
       this.isUsed = isUsed;
       this.setTimestamp = setTimestamp;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public String getCaptchaId() {
        return this.captchaId;
    }
    
    public void setCaptchaId(String captchaId) {
        this.captchaId = captchaId;
    }
    public String getCaptchaCode() {
        return this.captchaCode;
    }
    
    public void setCaptchaCode(String captchaCode) {
        this.captchaCode = captchaCode;
    }
    public boolean isIsUsed() {
        return this.isUsed;
    }
    
    public void setIsUsed(boolean isUsed) {
        this.isUsed = isUsed;
    }
    public long getSetTimestamp() {
        return this.setTimestamp;
    }
    
    public void setSetTimestamp(long setTimestamp) {
        this.setTimestamp = setTimestamp;
    }




}


