package hibernate.mapping;
// Generated Aug 21, 2018 4:05:27 PM by Hibernate Tools 4.3.1



/**
 * Chatuseroptions generated by hbm2java
 */
public class Chatuseroptions  implements java.io.Serializable {


     private long autoId;
     private String deviceId;
     private long userOne;
     private long userTwo;
     private boolean likeDislike;
     private boolean talking;
     private boolean comment;
     private boolean share;
     private boolean chatImage;
     private boolean chatAudio;
     private boolean chatVideo;
     private boolean chatFile;
     private boolean chatGif;

    public Chatuseroptions() {
    }

    public Chatuseroptions(String deviceId, long userOne, long userTwo, boolean likeDislike, boolean talking, boolean comment, boolean share, boolean chatImage, boolean chatAudio, boolean chatVideo, boolean chatFile, boolean chatGif) {
       this.deviceId = deviceId;
       this.userOne = userOne;
       this.userTwo = userTwo;
       this.likeDislike = likeDislike;
       this.talking = talking;
       this.comment = comment;
       this.share = share;
       this.chatImage = chatImage;
       this.chatAudio = chatAudio;
       this.chatVideo = chatVideo;
       this.chatFile = chatFile;
       this.chatGif = chatGif;
    }
   
    public long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(long autoId) {
        this.autoId = autoId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getUserOne() {
        return this.userOne;
    }
    
    public void setUserOne(long userOne) {
        this.userOne = userOne;
    }
    public long getUserTwo() {
        return this.userTwo;
    }
    
    public void setUserTwo(long userTwo) {
        this.userTwo = userTwo;
    }
    public boolean isLikeDislike() {
        return this.likeDislike;
    }
    
    public void setLikeDislike(boolean likeDislike) {
        this.likeDislike = likeDislike;
    }
    public boolean isTalking() {
        return this.talking;
    }
    
    public void setTalking(boolean talking) {
        this.talking = talking;
    }
    public boolean isComment() {
        return this.comment;
    }
    
    public void setComment(boolean comment) {
        this.comment = comment;
    }
    public boolean isShare() {
        return this.share;
    }
    
    public void setShare(boolean share) {
        this.share = share;
    }
    public boolean isChatImage() {
        return this.chatImage;
    }
    
    public void setChatImage(boolean chatImage) {
        this.chatImage = chatImage;
    }
    public boolean isChatAudio() {
        return this.chatAudio;
    }
    
    public void setChatAudio(boolean chatAudio) {
        this.chatAudio = chatAudio;
    }
    public boolean isChatVideo() {
        return this.chatVideo;
    }
    
    public void setChatVideo(boolean chatVideo) {
        this.chatVideo = chatVideo;
    }
    public boolean isChatFile() {
        return this.chatFile;
    }
    
    public void setChatFile(boolean chatFile) {
        this.chatFile = chatFile;
    }
    public boolean isChatGif() {
        return this.chatGif;
    }
    
    public void setChatGif(boolean chatGif) {
        this.chatGif = chatGif;
    }




}


