package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Chatnotifications generated by hbm2java
 */
public class Chatnotifications  implements java.io.Serializable {


     private String autoId;
     private String deviceId;
     private long userOne;
     private long userTwo;
     private long setTimestamp;
     private byte chatType;
     private byte readNotification;

    public Chatnotifications() {
    }

    public Chatnotifications(String autoId, String deviceId, long userOne, long userTwo, long setTimestamp, byte chatType, byte readNotification) {
       this.autoId = autoId;
       this.deviceId = deviceId;
       this.userOne = userOne;
       this.userTwo = userTwo;
       this.setTimestamp = setTimestamp;
       this.chatType = chatType;
       this.readNotification = readNotification;
    }
   
    public String getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(String autoId) {
        this.autoId = autoId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getUserOne() {
        return this.userOne;
    }
    
    public void setUserOne(long userOne) {
        this.userOne = userOne;
    }
    public long getUserTwo() {
        return this.userTwo;
    }
    
    public void setUserTwo(long userTwo) {
        this.userTwo = userTwo;
    }
    public long getSetTimestamp() {
        return this.setTimestamp;
    }
    
    public void setSetTimestamp(long setTimestamp) {
        this.setTimestamp = setTimestamp;
    }
    public byte getChatType() {
        return this.chatType;
    }
    
    public void setChatType(byte chatType) {
        this.chatType = chatType;
    }
    public byte getReadNotification() {
        return this.readNotification;
    }
    
    public void setReadNotification(byte readNotification) {
        this.readNotification = readNotification;
    }




}


