package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Invalidlogin generated by hbm2java
 */
public class Invalidlogin  implements java.io.Serializable {


     private String deviceId;
     private long userId;
     private long loginTimestamp;

    public Invalidlogin() {
    }

    public Invalidlogin(String deviceId, long userId, long loginTimestamp) {
       this.deviceId = deviceId;
       this.userId = userId;
       this.loginTimestamp = loginTimestamp;
    }
   
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getLoginTimestamp() {
        return this.loginTimestamp;
    }
    
    public void setLoginTimestamp(long loginTimestamp) {
        this.loginTimestamp = loginTimestamp;
    }




}


