package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Otpcode generated by hbm2java
 */
public class Otpcode  implements java.io.Serializable {


     private long userId;
     private long setTimestamp;
     private int verifyCode;
     private byte attempts;

    public Otpcode() {
    }

    public Otpcode(long userId, long setTimestamp, int verifyCode, byte attempts) {
       this.userId = userId;
       this.setTimestamp = setTimestamp;
       this.verifyCode = verifyCode;
       this.attempts = attempts;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getSetTimestamp() {
        return this.setTimestamp;
    }
    
    public void setSetTimestamp(long setTimestamp) {
        this.setTimestamp = setTimestamp;
    }
    public int getVerifyCode() {
        return this.verifyCode;
    }
    
    public void setVerifyCode(int verifyCode) {
        this.verifyCode = verifyCode;
    }
    public byte getAttempts() {
        return this.attempts;
    }
    
    public void setAttempts(byte attempts) {
        this.attempts = attempts;
    }




}


