package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Secondaryinfo generated by hbm2java
 */
public class Secondaryinfo  implements java.io.Serializable {


     private Long autoId;
     private long userId;
     private String deviceId;
     private String defaultId;
     private long timestampVal;
     private Boolean deleted;
     private String securPass;
     private Long securTstmp;
     private Byte securAttempt;
     private String edsecurPass;
     private Long edsecurTstmp;
     private Byte edsecurAttempt;
     private String picId;
     private String school;
     private Byte schoolpri;
     private String schoolentr;
     private String schoolleave;
     private String schooldesc;
     private Boolean schoolPrivacy;
     private String gradcollege;
     private Byte gradcollpri;
     private String gradcollentr;
     private String gradcollleave;
     private String gradcolldesc;
     private Boolean gradcollPrivacy;
     private String graduniver;
     private Byte graduniverpri;
     private String graduniverentr;
     private String graduniverleave;
     private String graduniverdesc;
     private Boolean graduniverPrivacy;
     private String pogradcollege;
     private Byte pogradcollpri;
     private String pogradcollentr;
     private String pogradcollleave;
     private String pogradcolldesc;
     private Boolean pogradcollPrivacy;
     private String pograduniver;
     private Byte pograduniverpri;
     private String pograduniverentr;
     private String pograduniverleave;
     private String pograduniverdesc;
     private Boolean pograduniverPrivacy;
     private String worktype;
     private String workplace;
     private Byte workpri;
     private String workstart;
     private String workleave;
     private String workdesc;
     private String currcity;
     private String hometown;
     private Byte locationpri;
     private String locationdesc;
     private String movedfrom;
     private String movedto;
     private Byte movedpri;
     private String movedtime;
     private String moveddesc;
     private String mobilenumber;
     private Byte mobilepri;
     private Byte mobiletype;
     private String mobiledesc;
     private String email;
     private Byte emailpri;
     private Byte emailtype;
     private String emaildesc;
     private String website;
     private Byte websitepri;
     private Byte websitetype;
     private String websitedesc;
     private String hobbies;
     private Byte hobbpri;
     private String hobbiesdesc;
     private String relatiname;
     private Byte relationship;
     private String relatitime;
     private Byte relatipri;
     private String relatidesc;
     private String relatname;
     private Byte relation;
     private Byte relatpri;
     private String relatdesc;
     private String languages;
     private Byte langpri;
     private String langdesc;
     private String religion;
     private Byte religpri;
     private String religdesc;
     private String behaviour;
     private Byte behavpri;
     private String behavdesc;
     private String myself;
     private Byte myselpri;
     private String myseldesc;
     private String categname;
     private String categvalue;
     private Byte categpri;
     private String categdesc;

    public Secondaryinfo() {
    }

	
    public Secondaryinfo(long userId, String deviceId, String defaultId, long timestampVal) {
        this.userId = userId;
        this.deviceId = deviceId;
        this.defaultId = defaultId;
        this.timestampVal = timestampVal;
    }
    public Secondaryinfo(long userId, String deviceId, String defaultId, long timestampVal, Boolean deleted, String securPass, Long securTstmp, Byte securAttempt, String edsecurPass, Long edsecurTstmp, Byte edsecurAttempt, String picId, String school, Byte schoolpri, String schoolentr, String schoolleave, String schooldesc, Boolean schoolPrivacy, String gradcollege, Byte gradcollpri, String gradcollentr, String gradcollleave, String gradcolldesc, Boolean gradcollPrivacy, String graduniver, Byte graduniverpri, String graduniverentr, String graduniverleave, String graduniverdesc, Boolean graduniverPrivacy, String pogradcollege, Byte pogradcollpri, String pogradcollentr, String pogradcollleave, String pogradcolldesc, Boolean pogradcollPrivacy, String pograduniver, Byte pograduniverpri, String pograduniverentr, String pograduniverleave, String pograduniverdesc, Boolean pograduniverPrivacy, String worktype, String workplace, Byte workpri, String workstart, String workleave, String workdesc, String currcity, String hometown, Byte locationpri, String locationdesc, String movedfrom, String movedto, Byte movedpri, String movedtime, String moveddesc, String mobilenumber, Byte mobilepri, Byte mobiletype, String mobiledesc, String email, Byte emailpri, Byte emailtype, String emaildesc, String website, Byte websitepri, Byte websitetype, String websitedesc, String hobbies, Byte hobbpri, String hobbiesdesc, String relatiname, Byte relationship, String relatitime, Byte relatipri, String relatidesc, String relatname, Byte relation, Byte relatpri, String relatdesc, String languages, Byte langpri, String langdesc, String religion, Byte religpri, String religdesc, String behaviour, Byte behavpri, String behavdesc, String myself, Byte myselpri, String myseldesc, String categname, String categvalue, Byte categpri, String categdesc) {
       this.userId = userId;
       this.deviceId = deviceId;
       this.defaultId = defaultId;
       this.timestampVal = timestampVal;
       this.deleted = deleted;
       this.securPass = securPass;
       this.securTstmp = securTstmp;
       this.securAttempt = securAttempt;
       this.edsecurPass = edsecurPass;
       this.edsecurTstmp = edsecurTstmp;
       this.edsecurAttempt = edsecurAttempt;
       this.picId = picId;
       this.school = school;
       this.schoolpri = schoolpri;
       this.schoolentr = schoolentr;
       this.schoolleave = schoolleave;
       this.schooldesc = schooldesc;
       this.schoolPrivacy = schoolPrivacy;
       this.gradcollege = gradcollege;
       this.gradcollpri = gradcollpri;
       this.gradcollentr = gradcollentr;
       this.gradcollleave = gradcollleave;
       this.gradcolldesc = gradcolldesc;
       this.gradcollPrivacy = gradcollPrivacy;
       this.graduniver = graduniver;
       this.graduniverpri = graduniverpri;
       this.graduniverentr = graduniverentr;
       this.graduniverleave = graduniverleave;
       this.graduniverdesc = graduniverdesc;
       this.graduniverPrivacy = graduniverPrivacy;
       this.pogradcollege = pogradcollege;
       this.pogradcollpri = pogradcollpri;
       this.pogradcollentr = pogradcollentr;
       this.pogradcollleave = pogradcollleave;
       this.pogradcolldesc = pogradcolldesc;
       this.pogradcollPrivacy = pogradcollPrivacy;
       this.pograduniver = pograduniver;
       this.pograduniverpri = pograduniverpri;
       this.pograduniverentr = pograduniverentr;
       this.pograduniverleave = pograduniverleave;
       this.pograduniverdesc = pograduniverdesc;
       this.pograduniverPrivacy = pograduniverPrivacy;
       this.worktype = worktype;
       this.workplace = workplace;
       this.workpri = workpri;
       this.workstart = workstart;
       this.workleave = workleave;
       this.workdesc = workdesc;
       this.currcity = currcity;
       this.hometown = hometown;
       this.locationpri = locationpri;
       this.locationdesc = locationdesc;
       this.movedfrom = movedfrom;
       this.movedto = movedto;
       this.movedpri = movedpri;
       this.movedtime = movedtime;
       this.moveddesc = moveddesc;
       this.mobilenumber = mobilenumber;
       this.mobilepri = mobilepri;
       this.mobiletype = mobiletype;
       this.mobiledesc = mobiledesc;
       this.email = email;
       this.emailpri = emailpri;
       this.emailtype = emailtype;
       this.emaildesc = emaildesc;
       this.website = website;
       this.websitepri = websitepri;
       this.websitetype = websitetype;
       this.websitedesc = websitedesc;
       this.hobbies = hobbies;
       this.hobbpri = hobbpri;
       this.hobbiesdesc = hobbiesdesc;
       this.relatiname = relatiname;
       this.relationship = relationship;
       this.relatitime = relatitime;
       this.relatipri = relatipri;
       this.relatidesc = relatidesc;
       this.relatname = relatname;
       this.relation = relation;
       this.relatpri = relatpri;
       this.relatdesc = relatdesc;
       this.languages = languages;
       this.langpri = langpri;
       this.langdesc = langdesc;
       this.religion = religion;
       this.religpri = religpri;
       this.religdesc = religdesc;
       this.behaviour = behaviour;
       this.behavpri = behavpri;
       this.behavdesc = behavdesc;
       this.myself = myself;
       this.myselpri = myselpri;
       this.myseldesc = myseldesc;
       this.categname = categname;
       this.categvalue = categvalue;
       this.categpri = categpri;
       this.categdesc = categdesc;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public String getDefaultId() {
        return this.defaultId;
    }
    
    public void setDefaultId(String defaultId) {
        this.defaultId = defaultId;
    }
    public long getTimestampVal() {
        return this.timestampVal;
    }
    
    public void setTimestampVal(long timestampVal) {
        this.timestampVal = timestampVal;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public String getSecurPass() {
        return this.securPass;
    }
    
    public void setSecurPass(String securPass) {
        this.securPass = securPass;
    }
    public Long getSecurTstmp() {
        return this.securTstmp;
    }
    
    public void setSecurTstmp(Long securTstmp) {
        this.securTstmp = securTstmp;
    }
    public Byte getSecurAttempt() {
        return this.securAttempt;
    }
    
    public void setSecurAttempt(Byte securAttempt) {
        this.securAttempt = securAttempt;
    }
    public String getEdsecurPass() {
        return this.edsecurPass;
    }
    
    public void setEdsecurPass(String edsecurPass) {
        this.edsecurPass = edsecurPass;
    }
    public Long getEdsecurTstmp() {
        return this.edsecurTstmp;
    }
    
    public void setEdsecurTstmp(Long edsecurTstmp) {
        this.edsecurTstmp = edsecurTstmp;
    }
    public Byte getEdsecurAttempt() {
        return this.edsecurAttempt;
    }
    
    public void setEdsecurAttempt(Byte edsecurAttempt) {
        this.edsecurAttempt = edsecurAttempt;
    }
    public String getPicId() {
        return this.picId;
    }
    
    public void setPicId(String picId) {
        this.picId = picId;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public Byte getSchoolpri() {
        return this.schoolpri;
    }
    
    public void setSchoolpri(Byte schoolpri) {
        this.schoolpri = schoolpri;
    }
    public String getSchoolentr() {
        return this.schoolentr;
    }
    
    public void setSchoolentr(String schoolentr) {
        this.schoolentr = schoolentr;
    }
    public String getSchoolleave() {
        return this.schoolleave;
    }
    
    public void setSchoolleave(String schoolleave) {
        this.schoolleave = schoolleave;
    }
    public String getSchooldesc() {
        return this.schooldesc;
    }
    
    public void setSchooldesc(String schooldesc) {
        this.schooldesc = schooldesc;
    }
    public Boolean getSchoolPrivacy() {
        return this.schoolPrivacy;
    }
    
    public void setSchoolPrivacy(Boolean schoolPrivacy) {
        this.schoolPrivacy = schoolPrivacy;
    }
    public String getGradcollege() {
        return this.gradcollege;
    }
    
    public void setGradcollege(String gradcollege) {
        this.gradcollege = gradcollege;
    }
    public Byte getGradcollpri() {
        return this.gradcollpri;
    }
    
    public void setGradcollpri(Byte gradcollpri) {
        this.gradcollpri = gradcollpri;
    }
    public String getGradcollentr() {
        return this.gradcollentr;
    }
    
    public void setGradcollentr(String gradcollentr) {
        this.gradcollentr = gradcollentr;
    }
    public String getGradcollleave() {
        return this.gradcollleave;
    }
    
    public void setGradcollleave(String gradcollleave) {
        this.gradcollleave = gradcollleave;
    }
    public String getGradcolldesc() {
        return this.gradcolldesc;
    }
    
    public void setGradcolldesc(String gradcolldesc) {
        this.gradcolldesc = gradcolldesc;
    }
    public Boolean getGradcollPrivacy() {
        return this.gradcollPrivacy;
    }
    
    public void setGradcollPrivacy(Boolean gradcollPrivacy) {
        this.gradcollPrivacy = gradcollPrivacy;
    }
    public String getGraduniver() {
        return this.graduniver;
    }
    
    public void setGraduniver(String graduniver) {
        this.graduniver = graduniver;
    }
    public Byte getGraduniverpri() {
        return this.graduniverpri;
    }
    
    public void setGraduniverpri(Byte graduniverpri) {
        this.graduniverpri = graduniverpri;
    }
    public String getGraduniverentr() {
        return this.graduniverentr;
    }
    
    public void setGraduniverentr(String graduniverentr) {
        this.graduniverentr = graduniverentr;
    }
    public String getGraduniverleave() {
        return this.graduniverleave;
    }
    
    public void setGraduniverleave(String graduniverleave) {
        this.graduniverleave = graduniverleave;
    }
    public String getGraduniverdesc() {
        return this.graduniverdesc;
    }
    
    public void setGraduniverdesc(String graduniverdesc) {
        this.graduniverdesc = graduniverdesc;
    }
    public Boolean getGraduniverPrivacy() {
        return this.graduniverPrivacy;
    }
    
    public void setGraduniverPrivacy(Boolean graduniverPrivacy) {
        this.graduniverPrivacy = graduniverPrivacy;
    }
    public String getPogradcollege() {
        return this.pogradcollege;
    }
    
    public void setPogradcollege(String pogradcollege) {
        this.pogradcollege = pogradcollege;
    }
    public Byte getPogradcollpri() {
        return this.pogradcollpri;
    }
    
    public void setPogradcollpri(Byte pogradcollpri) {
        this.pogradcollpri = pogradcollpri;
    }
    public String getPogradcollentr() {
        return this.pogradcollentr;
    }
    
    public void setPogradcollentr(String pogradcollentr) {
        this.pogradcollentr = pogradcollentr;
    }
    public String getPogradcollleave() {
        return this.pogradcollleave;
    }
    
    public void setPogradcollleave(String pogradcollleave) {
        this.pogradcollleave = pogradcollleave;
    }
    public String getPogradcolldesc() {
        return this.pogradcolldesc;
    }
    
    public void setPogradcolldesc(String pogradcolldesc) {
        this.pogradcolldesc = pogradcolldesc;
    }
    public Boolean getPogradcollPrivacy() {
        return this.pogradcollPrivacy;
    }
    
    public void setPogradcollPrivacy(Boolean pogradcollPrivacy) {
        this.pogradcollPrivacy = pogradcollPrivacy;
    }
    public String getPograduniver() {
        return this.pograduniver;
    }
    
    public void setPograduniver(String pograduniver) {
        this.pograduniver = pograduniver;
    }
    public Byte getPograduniverpri() {
        return this.pograduniverpri;
    }
    
    public void setPograduniverpri(Byte pograduniverpri) {
        this.pograduniverpri = pograduniverpri;
    }
    public String getPograduniverentr() {
        return this.pograduniverentr;
    }
    
    public void setPograduniverentr(String pograduniverentr) {
        this.pograduniverentr = pograduniverentr;
    }
    public String getPograduniverleave() {
        return this.pograduniverleave;
    }
    
    public void setPograduniverleave(String pograduniverleave) {
        this.pograduniverleave = pograduniverleave;
    }
    public String getPograduniverdesc() {
        return this.pograduniverdesc;
    }
    
    public void setPograduniverdesc(String pograduniverdesc) {
        this.pograduniverdesc = pograduniverdesc;
    }
    public Boolean getPograduniverPrivacy() {
        return this.pograduniverPrivacy;
    }
    
    public void setPograduniverPrivacy(Boolean pograduniverPrivacy) {
        this.pograduniverPrivacy = pograduniverPrivacy;
    }
    public String getWorktype() {
        return this.worktype;
    }
    
    public void setWorktype(String worktype) {
        this.worktype = worktype;
    }
    public String getWorkplace() {
        return this.workplace;
    }
    
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }
    public Byte getWorkpri() {
        return this.workpri;
    }
    
    public void setWorkpri(Byte workpri) {
        this.workpri = workpri;
    }
    public String getWorkstart() {
        return this.workstart;
    }
    
    public void setWorkstart(String workstart) {
        this.workstart = workstart;
    }
    public String getWorkleave() {
        return this.workleave;
    }
    
    public void setWorkleave(String workleave) {
        this.workleave = workleave;
    }
    public String getWorkdesc() {
        return this.workdesc;
    }
    
    public void setWorkdesc(String workdesc) {
        this.workdesc = workdesc;
    }
    public String getCurrcity() {
        return this.currcity;
    }
    
    public void setCurrcity(String currcity) {
        this.currcity = currcity;
    }
    public String getHometown() {
        return this.hometown;
    }
    
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }
    public Byte getLocationpri() {
        return this.locationpri;
    }
    
    public void setLocationpri(Byte locationpri) {
        this.locationpri = locationpri;
    }
    public String getLocationdesc() {
        return this.locationdesc;
    }
    
    public void setLocationdesc(String locationdesc) {
        this.locationdesc = locationdesc;
    }
    public String getMovedfrom() {
        return this.movedfrom;
    }
    
    public void setMovedfrom(String movedfrom) {
        this.movedfrom = movedfrom;
    }
    public String getMovedto() {
        return this.movedto;
    }
    
    public void setMovedto(String movedto) {
        this.movedto = movedto;
    }
    public Byte getMovedpri() {
        return this.movedpri;
    }
    
    public void setMovedpri(Byte movedpri) {
        this.movedpri = movedpri;
    }
    public String getMovedtime() {
        return this.movedtime;
    }
    
    public void setMovedtime(String movedtime) {
        this.movedtime = movedtime;
    }
    public String getMoveddesc() {
        return this.moveddesc;
    }
    
    public void setMoveddesc(String moveddesc) {
        this.moveddesc = moveddesc;
    }
    public String getMobilenumber() {
        return this.mobilenumber;
    }
    
    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }
    public Byte getMobilepri() {
        return this.mobilepri;
    }
    
    public void setMobilepri(Byte mobilepri) {
        this.mobilepri = mobilepri;
    }
    public Byte getMobiletype() {
        return this.mobiletype;
    }
    
    public void setMobiletype(Byte mobiletype) {
        this.mobiletype = mobiletype;
    }
    public String getMobiledesc() {
        return this.mobiledesc;
    }
    
    public void setMobiledesc(String mobiledesc) {
        this.mobiledesc = mobiledesc;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Byte getEmailpri() {
        return this.emailpri;
    }
    
    public void setEmailpri(Byte emailpri) {
        this.emailpri = emailpri;
    }
    public Byte getEmailtype() {
        return this.emailtype;
    }
    
    public void setEmailtype(Byte emailtype) {
        this.emailtype = emailtype;
    }
    public String getEmaildesc() {
        return this.emaildesc;
    }
    
    public void setEmaildesc(String emaildesc) {
        this.emaildesc = emaildesc;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Byte getWebsitepri() {
        return this.websitepri;
    }
    
    public void setWebsitepri(Byte websitepri) {
        this.websitepri = websitepri;
    }
    public Byte getWebsitetype() {
        return this.websitetype;
    }
    
    public void setWebsitetype(Byte websitetype) {
        this.websitetype = websitetype;
    }
    public String getWebsitedesc() {
        return this.websitedesc;
    }
    
    public void setWebsitedesc(String websitedesc) {
        this.websitedesc = websitedesc;
    }
    public String getHobbies() {
        return this.hobbies;
    }
    
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }
    public Byte getHobbpri() {
        return this.hobbpri;
    }
    
    public void setHobbpri(Byte hobbpri) {
        this.hobbpri = hobbpri;
    }
    public String getHobbiesdesc() {
        return this.hobbiesdesc;
    }
    
    public void setHobbiesdesc(String hobbiesdesc) {
        this.hobbiesdesc = hobbiesdesc;
    }
    public String getRelatiname() {
        return this.relatiname;
    }
    
    public void setRelatiname(String relatiname) {
        this.relatiname = relatiname;
    }
    public Byte getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(Byte relationship) {
        this.relationship = relationship;
    }
    public String getRelatitime() {
        return this.relatitime;
    }
    
    public void setRelatitime(String relatitime) {
        this.relatitime = relatitime;
    }
    public Byte getRelatipri() {
        return this.relatipri;
    }
    
    public void setRelatipri(Byte relatipri) {
        this.relatipri = relatipri;
    }
    public String getRelatidesc() {
        return this.relatidesc;
    }
    
    public void setRelatidesc(String relatidesc) {
        this.relatidesc = relatidesc;
    }
    public String getRelatname() {
        return this.relatname;
    }
    
    public void setRelatname(String relatname) {
        this.relatname = relatname;
    }
    public Byte getRelation() {
        return this.relation;
    }
    
    public void setRelation(Byte relation) {
        this.relation = relation;
    }
    public Byte getRelatpri() {
        return this.relatpri;
    }
    
    public void setRelatpri(Byte relatpri) {
        this.relatpri = relatpri;
    }
    public String getRelatdesc() {
        return this.relatdesc;
    }
    
    public void setRelatdesc(String relatdesc) {
        this.relatdesc = relatdesc;
    }
    public String getLanguages() {
        return this.languages;
    }
    
    public void setLanguages(String languages) {
        this.languages = languages;
    }
    public Byte getLangpri() {
        return this.langpri;
    }
    
    public void setLangpri(Byte langpri) {
        this.langpri = langpri;
    }
    public String getLangdesc() {
        return this.langdesc;
    }
    
    public void setLangdesc(String langdesc) {
        this.langdesc = langdesc;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public Byte getReligpri() {
        return this.religpri;
    }
    
    public void setReligpri(Byte religpri) {
        this.religpri = religpri;
    }
    public String getReligdesc() {
        return this.religdesc;
    }
    
    public void setReligdesc(String religdesc) {
        this.religdesc = religdesc;
    }
    public String getBehaviour() {
        return this.behaviour;
    }
    
    public void setBehaviour(String behaviour) {
        this.behaviour = behaviour;
    }
    public Byte getBehavpri() {
        return this.behavpri;
    }
    
    public void setBehavpri(Byte behavpri) {
        this.behavpri = behavpri;
    }
    public String getBehavdesc() {
        return this.behavdesc;
    }
    
    public void setBehavdesc(String behavdesc) {
        this.behavdesc = behavdesc;
    }
    public String getMyself() {
        return this.myself;
    }
    
    public void setMyself(String myself) {
        this.myself = myself;
    }
    public Byte getMyselpri() {
        return this.myselpri;
    }
    
    public void setMyselpri(Byte myselpri) {
        this.myselpri = myselpri;
    }
    public String getMyseldesc() {
        return this.myseldesc;
    }
    
    public void setMyseldesc(String myseldesc) {
        this.myseldesc = myseldesc;
    }
    public String getCategname() {
        return this.categname;
    }
    
    public void setCategname(String categname) {
        this.categname = categname;
    }
    public String getCategvalue() {
        return this.categvalue;
    }
    
    public void setCategvalue(String categvalue) {
        this.categvalue = categvalue;
    }
    public Byte getCategpri() {
        return this.categpri;
    }
    
    public void setCategpri(Byte categpri) {
        this.categpri = categpri;
    }
    public String getCategdesc() {
        return this.categdesc;
    }
    
    public void setCategdesc(String categdesc) {
        this.categdesc = categdesc;
    }




}


