package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Showhideeditaccpic generated by hbm2java
 */
public class Showhideeditaccpic  implements java.io.Serializable {


     private Long autoId;
     private long userId;
     private String deviceId;
     private boolean info;
     private boolean moreinfo;
     private boolean setting;
     private boolean security;
     private boolean accpic;
     private boolean uploadnew;
     private boolean remove;
     private boolean deletes;
     private boolean download;
     private boolean pictime;
     private boolean likes;
     private boolean dislike;
     private boolean talking;
     private boolean comment;
     private boolean share;
     private boolean see;
     private boolean dodownload;
     private boolean lidislike;
     private boolean seelidislike;
     private boolean dotalking;
     private boolean seetalking;
     private boolean docomment;
     private boolean seecomment;
     private boolean doshare;
     private boolean seeshare;
     private boolean prilike;
     private boolean pridislike;
     private boolean pritalking;
     private boolean pricomment;
     private boolean prishare;
     private boolean showhide;

    public Showhideeditaccpic() {
    }

    public Showhideeditaccpic(long userId, String deviceId, boolean info, boolean moreinfo, boolean setting, boolean security, boolean accpic, boolean uploadnew, boolean remove, boolean deletes, boolean download, boolean pictime, boolean likes, boolean dislike, boolean talking, boolean comment, boolean share, boolean see, boolean dodownload, boolean lidislike, boolean seelidislike, boolean dotalking, boolean seetalking, boolean docomment, boolean seecomment, boolean doshare, boolean seeshare, boolean prilike, boolean pridislike, boolean pritalking, boolean pricomment, boolean prishare, boolean showhide) {
       this.userId = userId;
       this.deviceId = deviceId;
       this.info = info;
       this.moreinfo = moreinfo;
       this.setting = setting;
       this.security = security;
       this.accpic = accpic;
       this.uploadnew = uploadnew;
       this.remove = remove;
       this.deletes = deletes;
       this.download = download;
       this.pictime = pictime;
       this.likes = likes;
       this.dislike = dislike;
       this.talking = talking;
       this.comment = comment;
       this.share = share;
       this.see = see;
       this.dodownload = dodownload;
       this.lidislike = lidislike;
       this.seelidislike = seelidislike;
       this.dotalking = dotalking;
       this.seetalking = seetalking;
       this.docomment = docomment;
       this.seecomment = seecomment;
       this.doshare = doshare;
       this.seeshare = seeshare;
       this.prilike = prilike;
       this.pridislike = pridislike;
       this.pritalking = pritalking;
       this.pricomment = pricomment;
       this.prishare = prishare;
       this.showhide = showhide;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public boolean isInfo() {
        return this.info;
    }
    
    public void setInfo(boolean info) {
        this.info = info;
    }
    public boolean isMoreinfo() {
        return this.moreinfo;
    }
    
    public void setMoreinfo(boolean moreinfo) {
        this.moreinfo = moreinfo;
    }
    public boolean isSetting() {
        return this.setting;
    }
    
    public void setSetting(boolean setting) {
        this.setting = setting;
    }
    public boolean isSecurity() {
        return this.security;
    }
    
    public void setSecurity(boolean security) {
        this.security = security;
    }
    public boolean isAccpic() {
        return this.accpic;
    }
    
    public void setAccpic(boolean accpic) {
        this.accpic = accpic;
    }
    public boolean isUploadnew() {
        return this.uploadnew;
    }
    
    public void setUploadnew(boolean uploadnew) {
        this.uploadnew = uploadnew;
    }
    public boolean isRemove() {
        return this.remove;
    }
    
    public void setRemove(boolean remove) {
        this.remove = remove;
    }
    public boolean isDeletes() {
        return this.deletes;
    }
    
    public void setDeletes(boolean deletes) {
        this.deletes = deletes;
    }
    public boolean isDownload() {
        return this.download;
    }
    
    public void setDownload(boolean download) {
        this.download = download;
    }
    public boolean isPictime() {
        return this.pictime;
    }
    
    public void setPictime(boolean pictime) {
        this.pictime = pictime;
    }
    public boolean isLikes() {
        return this.likes;
    }
    
    public void setLikes(boolean likes) {
        this.likes = likes;
    }
    public boolean isDislike() {
        return this.dislike;
    }
    
    public void setDislike(boolean dislike) {
        this.dislike = dislike;
    }
    public boolean isTalking() {
        return this.talking;
    }
    
    public void setTalking(boolean talking) {
        this.talking = talking;
    }
    public boolean isComment() {
        return this.comment;
    }
    
    public void setComment(boolean comment) {
        this.comment = comment;
    }
    public boolean isShare() {
        return this.share;
    }
    
    public void setShare(boolean share) {
        this.share = share;
    }
    public boolean isSee() {
        return this.see;
    }
    
    public void setSee(boolean see) {
        this.see = see;
    }
    public boolean isDodownload() {
        return this.dodownload;
    }
    
    public void setDodownload(boolean dodownload) {
        this.dodownload = dodownload;
    }
    public boolean isLidislike() {
        return this.lidislike;
    }
    
    public void setLidislike(boolean lidislike) {
        this.lidislike = lidislike;
    }
    public boolean isSeelidislike() {
        return this.seelidislike;
    }
    
    public void setSeelidislike(boolean seelidislike) {
        this.seelidislike = seelidislike;
    }
    public boolean isDotalking() {
        return this.dotalking;
    }
    
    public void setDotalking(boolean dotalking) {
        this.dotalking = dotalking;
    }
    public boolean isSeetalking() {
        return this.seetalking;
    }
    
    public void setSeetalking(boolean seetalking) {
        this.seetalking = seetalking;
    }
    public boolean isDocomment() {
        return this.docomment;
    }
    
    public void setDocomment(boolean docomment) {
        this.docomment = docomment;
    }
    public boolean isSeecomment() {
        return this.seecomment;
    }
    
    public void setSeecomment(boolean seecomment) {
        this.seecomment = seecomment;
    }
    public boolean isDoshare() {
        return this.doshare;
    }
    
    public void setDoshare(boolean doshare) {
        this.doshare = doshare;
    }
    public boolean isSeeshare() {
        return this.seeshare;
    }
    
    public void setSeeshare(boolean seeshare) {
        this.seeshare = seeshare;
    }
    public boolean isPrilike() {
        return this.prilike;
    }
    
    public void setPrilike(boolean prilike) {
        this.prilike = prilike;
    }
    public boolean isPridislike() {
        return this.pridislike;
    }
    
    public void setPridislike(boolean pridislike) {
        this.pridislike = pridislike;
    }
    public boolean isPritalking() {
        return this.pritalking;
    }
    
    public void setPritalking(boolean pritalking) {
        this.pritalking = pritalking;
    }
    public boolean isPricomment() {
        return this.pricomment;
    }
    
    public void setPricomment(boolean pricomment) {
        this.pricomment = pricomment;
    }
    public boolean isPrishare() {
        return this.prishare;
    }
    
    public void setPrishare(boolean prishare) {
        this.prishare = prishare;
    }
    public boolean isShowhide() {
        return this.showhide;
    }
    
    public void setShowhide(boolean showhide) {
        this.showhide = showhide;
    }




}


