package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Showhideuplaccpic generated by hbm2java
 */
public class Showhideuplaccpic  implements java.io.Serializable {


     private Long autoId;
     private long userId;
     private String deviceId;
     private boolean info;
     private boolean moreinfo;
     private boolean setting;
     private boolean security;
     private boolean picpreview;
     private boolean choosepic;
     private boolean see;
     private boolean dodownload;
     private boolean lidislike;
     private boolean seelidislike;
     private boolean dotalking;
     private boolean seetalking;
     private boolean docomment;
     private boolean seecomment;
     private boolean doshare;
     private boolean seeshare;
     private boolean prilike;
     private boolean pridislike;
     private boolean pritalking;
     private boolean pricomment;
     private boolean prishare;
     private byte defsee;
     private byte defdodownload;
     private byte deflidislike;
     private byte defseelidislike;
     private byte defdotalking;
     private byte defseetalking;
     private byte defdocomment;
     private byte defseecomment;
     private byte defdoshare;
     private byte defseeshare;
     private boolean defprilike;
     private boolean defpridislike;
     private boolean defpritalking;
     private boolean defpricomment;
     private boolean defprishare;
     private boolean previouspics;
     private boolean showhide;

    public Showhideuplaccpic() {
    }

    public Showhideuplaccpic(long userId, String deviceId, boolean info, boolean moreinfo, boolean setting, boolean security, boolean picpreview, boolean choosepic, boolean see, boolean dodownload, boolean lidislike, boolean seelidislike, boolean dotalking, boolean seetalking, boolean docomment, boolean seecomment, boolean doshare, boolean seeshare, boolean prilike, boolean pridislike, boolean pritalking, boolean pricomment, boolean prishare, byte defsee, byte defdodownload, byte deflidislike, byte defseelidislike, byte defdotalking, byte defseetalking, byte defdocomment, byte defseecomment, byte defdoshare, byte defseeshare, boolean defprilike, boolean defpridislike, boolean defpritalking, boolean defpricomment, boolean defprishare, boolean previouspics, boolean showhide) {
       this.userId = userId;
       this.deviceId = deviceId;
       this.info = info;
       this.moreinfo = moreinfo;
       this.setting = setting;
       this.security = security;
       this.picpreview = picpreview;
       this.choosepic = choosepic;
       this.see = see;
       this.dodownload = dodownload;
       this.lidislike = lidislike;
       this.seelidislike = seelidislike;
       this.dotalking = dotalking;
       this.seetalking = seetalking;
       this.docomment = docomment;
       this.seecomment = seecomment;
       this.doshare = doshare;
       this.seeshare = seeshare;
       this.prilike = prilike;
       this.pridislike = pridislike;
       this.pritalking = pritalking;
       this.pricomment = pricomment;
       this.prishare = prishare;
       this.defsee = defsee;
       this.defdodownload = defdodownload;
       this.deflidislike = deflidislike;
       this.defseelidislike = defseelidislike;
       this.defdotalking = defdotalking;
       this.defseetalking = defseetalking;
       this.defdocomment = defdocomment;
       this.defseecomment = defseecomment;
       this.defdoshare = defdoshare;
       this.defseeshare = defseeshare;
       this.defprilike = defprilike;
       this.defpridislike = defpridislike;
       this.defpritalking = defpritalking;
       this.defpricomment = defpricomment;
       this.defprishare = defprishare;
       this.previouspics = previouspics;
       this.showhide = showhide;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public boolean isInfo() {
        return this.info;
    }
    
    public void setInfo(boolean info) {
        this.info = info;
    }
    public boolean isMoreinfo() {
        return this.moreinfo;
    }
    
    public void setMoreinfo(boolean moreinfo) {
        this.moreinfo = moreinfo;
    }
    public boolean isSetting() {
        return this.setting;
    }
    
    public void setSetting(boolean setting) {
        this.setting = setting;
    }
    public boolean isSecurity() {
        return this.security;
    }
    
    public void setSecurity(boolean security) {
        this.security = security;
    }
    public boolean isPicpreview() {
        return this.picpreview;
    }
    
    public void setPicpreview(boolean picpreview) {
        this.picpreview = picpreview;
    }
    public boolean isChoosepic() {
        return this.choosepic;
    }
    
    public void setChoosepic(boolean choosepic) {
        this.choosepic = choosepic;
    }
    public boolean isSee() {
        return this.see;
    }
    
    public void setSee(boolean see) {
        this.see = see;
    }
    public boolean isDodownload() {
        return this.dodownload;
    }
    
    public void setDodownload(boolean dodownload) {
        this.dodownload = dodownload;
    }
    public boolean isLidislike() {
        return this.lidislike;
    }
    
    public void setLidislike(boolean lidislike) {
        this.lidislike = lidislike;
    }
    public boolean isSeelidislike() {
        return this.seelidislike;
    }
    
    public void setSeelidislike(boolean seelidislike) {
        this.seelidislike = seelidislike;
    }
    public boolean isDotalking() {
        return this.dotalking;
    }
    
    public void setDotalking(boolean dotalking) {
        this.dotalking = dotalking;
    }
    public boolean isSeetalking() {
        return this.seetalking;
    }
    
    public void setSeetalking(boolean seetalking) {
        this.seetalking = seetalking;
    }
    public boolean isDocomment() {
        return this.docomment;
    }
    
    public void setDocomment(boolean docomment) {
        this.docomment = docomment;
    }
    public boolean isSeecomment() {
        return this.seecomment;
    }
    
    public void setSeecomment(boolean seecomment) {
        this.seecomment = seecomment;
    }
    public boolean isDoshare() {
        return this.doshare;
    }
    
    public void setDoshare(boolean doshare) {
        this.doshare = doshare;
    }
    public boolean isSeeshare() {
        return this.seeshare;
    }
    
    public void setSeeshare(boolean seeshare) {
        this.seeshare = seeshare;
    }
    public boolean isPrilike() {
        return this.prilike;
    }
    
    public void setPrilike(boolean prilike) {
        this.prilike = prilike;
    }
    public boolean isPridislike() {
        return this.pridislike;
    }
    
    public void setPridislike(boolean pridislike) {
        this.pridislike = pridislike;
    }
    public boolean isPritalking() {
        return this.pritalking;
    }
    
    public void setPritalking(boolean pritalking) {
        this.pritalking = pritalking;
    }
    public boolean isPricomment() {
        return this.pricomment;
    }
    
    public void setPricomment(boolean pricomment) {
        this.pricomment = pricomment;
    }
    public boolean isPrishare() {
        return this.prishare;
    }
    
    public void setPrishare(boolean prishare) {
        this.prishare = prishare;
    }
    public byte getDefsee() {
        return this.defsee;
    }
    
    public void setDefsee(byte defsee) {
        this.defsee = defsee;
    }
    public byte getDefdodownload() {
        return this.defdodownload;
    }
    
    public void setDefdodownload(byte defdodownload) {
        this.defdodownload = defdodownload;
    }
    public byte getDeflidislike() {
        return this.deflidislike;
    }
    
    public void setDeflidislike(byte deflidislike) {
        this.deflidislike = deflidislike;
    }
    public byte getDefseelidislike() {
        return this.defseelidislike;
    }
    
    public void setDefseelidislike(byte defseelidislike) {
        this.defseelidislike = defseelidislike;
    }
    public byte getDefdotalking() {
        return this.defdotalking;
    }
    
    public void setDefdotalking(byte defdotalking) {
        this.defdotalking = defdotalking;
    }
    public byte getDefseetalking() {
        return this.defseetalking;
    }
    
    public void setDefseetalking(byte defseetalking) {
        this.defseetalking = defseetalking;
    }
    public byte getDefdocomment() {
        return this.defdocomment;
    }
    
    public void setDefdocomment(byte defdocomment) {
        this.defdocomment = defdocomment;
    }
    public byte getDefseecomment() {
        return this.defseecomment;
    }
    
    public void setDefseecomment(byte defseecomment) {
        this.defseecomment = defseecomment;
    }
    public byte getDefdoshare() {
        return this.defdoshare;
    }
    
    public void setDefdoshare(byte defdoshare) {
        this.defdoshare = defdoshare;
    }
    public byte getDefseeshare() {
        return this.defseeshare;
    }
    
    public void setDefseeshare(byte defseeshare) {
        this.defseeshare = defseeshare;
    }
    public boolean isDefprilike() {
        return this.defprilike;
    }
    
    public void setDefprilike(boolean defprilike) {
        this.defprilike = defprilike;
    }
    public boolean isDefpridislike() {
        return this.defpridislike;
    }
    
    public void setDefpridislike(boolean defpridislike) {
        this.defpridislike = defpridislike;
    }
    public boolean isDefpritalking() {
        return this.defpritalking;
    }
    
    public void setDefpritalking(boolean defpritalking) {
        this.defpritalking = defpritalking;
    }
    public boolean isDefpricomment() {
        return this.defpricomment;
    }
    
    public void setDefpricomment(boolean defpricomment) {
        this.defpricomment = defpricomment;
    }
    public boolean isDefprishare() {
        return this.defprishare;
    }
    
    public void setDefprishare(boolean defprishare) {
        this.defprishare = defprishare;
    }
    public boolean isPreviouspics() {
        return this.previouspics;
    }
    
    public void setPreviouspics(boolean previouspics) {
        this.previouspics = previouspics;
    }
    public boolean isShowhide() {
        return this.showhide;
    }
    
    public void setShowhide(boolean showhide) {
        this.showhide = showhide;
    }




}


