package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Showhidemoreinfo generated by hbm2java
 */
public class Showhidemoreinfo  implements java.io.Serializable {


     private Long autoId;
     private long userId;
     private String deviceId;
     private boolean info;
     private boolean addmoin;
     private boolean setting;
     private boolean security;
     private boolean school;
     private boolean grcollege;
     private boolean gruniver;
     private boolean pogrcoll;
     private boolean pogruniv;
     private boolean works;
     private boolean moved;
     private boolean location;
     private boolean mobile;
     private boolean email;
     private boolean website;
     private boolean hobbies;
     private boolean relationship;
     private boolean relation;
     private boolean languages;
     private boolean religion;
     private boolean behaviour;
     private boolean myself;
     private boolean newcateg;

    public Showhidemoreinfo() {
    }

    public Showhidemoreinfo(long userId, String deviceId, boolean info, boolean addmoin, boolean setting, boolean security, boolean school, boolean grcollege, boolean gruniver, boolean pogrcoll, boolean pogruniv, boolean works, boolean moved, boolean location, boolean mobile, boolean email, boolean website, boolean hobbies, boolean relationship, boolean relation, boolean languages, boolean religion, boolean behaviour, boolean myself, boolean newcateg) {
       this.userId = userId;
       this.deviceId = deviceId;
       this.info = info;
       this.addmoin = addmoin;
       this.setting = setting;
       this.security = security;
       this.school = school;
       this.grcollege = grcollege;
       this.gruniver = gruniver;
       this.pogrcoll = pogrcoll;
       this.pogruniv = pogruniv;
       this.works = works;
       this.moved = moved;
       this.location = location;
       this.mobile = mobile;
       this.email = email;
       this.website = website;
       this.hobbies = hobbies;
       this.relationship = relationship;
       this.relation = relation;
       this.languages = languages;
       this.religion = religion;
       this.behaviour = behaviour;
       this.myself = myself;
       this.newcateg = newcateg;
    }
   
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public boolean isInfo() {
        return this.info;
    }
    
    public void setInfo(boolean info) {
        this.info = info;
    }
    public boolean isAddmoin() {
        return this.addmoin;
    }
    
    public void setAddmoin(boolean addmoin) {
        this.addmoin = addmoin;
    }
    public boolean isSetting() {
        return this.setting;
    }
    
    public void setSetting(boolean setting) {
        this.setting = setting;
    }
    public boolean isSecurity() {
        return this.security;
    }
    
    public void setSecurity(boolean security) {
        this.security = security;
    }
    public boolean isSchool() {
        return this.school;
    }
    
    public void setSchool(boolean school) {
        this.school = school;
    }
    public boolean isGrcollege() {
        return this.grcollege;
    }
    
    public void setGrcollege(boolean grcollege) {
        this.grcollege = grcollege;
    }
    public boolean isGruniver() {
        return this.gruniver;
    }
    
    public void setGruniver(boolean gruniver) {
        this.gruniver = gruniver;
    }
    public boolean isPogrcoll() {
        return this.pogrcoll;
    }
    
    public void setPogrcoll(boolean pogrcoll) {
        this.pogrcoll = pogrcoll;
    }
    public boolean isPogruniv() {
        return this.pogruniv;
    }
    
    public void setPogruniv(boolean pogruniv) {
        this.pogruniv = pogruniv;
    }
    public boolean isWorks() {
        return this.works;
    }
    
    public void setWorks(boolean works) {
        this.works = works;
    }
    public boolean isMoved() {
        return this.moved;
    }
    
    public void setMoved(boolean moved) {
        this.moved = moved;
    }
    public boolean isLocation() {
        return this.location;
    }
    
    public void setLocation(boolean location) {
        this.location = location;
    }
    public boolean isMobile() {
        return this.mobile;
    }
    
    public void setMobile(boolean mobile) {
        this.mobile = mobile;
    }
    public boolean isEmail() {
        return this.email;
    }
    
    public void setEmail(boolean email) {
        this.email = email;
    }
    public boolean isWebsite() {
        return this.website;
    }
    
    public void setWebsite(boolean website) {
        this.website = website;
    }
    public boolean isHobbies() {
        return this.hobbies;
    }
    
    public void setHobbies(boolean hobbies) {
        this.hobbies = hobbies;
    }
    public boolean isRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(boolean relationship) {
        this.relationship = relationship;
    }
    public boolean isRelation() {
        return this.relation;
    }
    
    public void setRelation(boolean relation) {
        this.relation = relation;
    }
    public boolean isLanguages() {
        return this.languages;
    }
    
    public void setLanguages(boolean languages) {
        this.languages = languages;
    }
    public boolean isReligion() {
        return this.religion;
    }
    
    public void setReligion(boolean religion) {
        this.religion = religion;
    }
    public boolean isBehaviour() {
        return this.behaviour;
    }
    
    public void setBehaviour(boolean behaviour) {
        this.behaviour = behaviour;
    }
    public boolean isMyself() {
        return this.myself;
    }
    
    public void setMyself(boolean myself) {
        this.myself = myself;
    }
    public boolean isNewcateg() {
        return this.newcateg;
    }
    
    public void setNewcateg(boolean newcateg) {
        this.newcateg = newcateg;
    }




}


