package hibernate.mapping;
// Generated Aug 31, 2018 6:19:28 PM by Hibernate Tools 4.3.1



/**
 * Showhidechatpage generated by hbm2java
 */
public class Showhidechatpage  implements java.io.Serializable {


     private long userId;
     private String deviceId;
     private boolean wooks;
     private boolean remove;
     private boolean block;
     private boolean starred;
     private boolean priority;
     private boolean mute;
     private boolean offchat;
     private boolean privacy;
     private boolean settings;
     private boolean msgTime;
     private byte msgLength;
     private byte defaultWallpaper;
     private String wallpaperId;

    public Showhidechatpage() {
    }

	
    public Showhidechatpage(long userId, String deviceId, boolean wooks, boolean remove, boolean block, boolean starred, boolean priority, boolean mute, boolean offchat, boolean privacy, boolean settings, boolean msgTime, byte msgLength, byte defaultWallpaper) {
        this.userId = userId;
        this.deviceId = deviceId;
        this.wooks = wooks;
        this.remove = remove;
        this.block = block;
        this.starred = starred;
        this.priority = priority;
        this.mute = mute;
        this.offchat = offchat;
        this.privacy = privacy;
        this.settings = settings;
        this.msgTime = msgTime;
        this.msgLength = msgLength;
        this.defaultWallpaper = defaultWallpaper;
    }
    public Showhidechatpage(long userId, String deviceId, boolean wooks, boolean remove, boolean block, boolean starred, boolean priority, boolean mute, boolean offchat, boolean privacy, boolean settings, boolean msgTime, byte msgLength, byte defaultWallpaper, String wallpaperId) {
       this.userId = userId;
       this.deviceId = deviceId;
       this.wooks = wooks;
       this.remove = remove;
       this.block = block;
       this.starred = starred;
       this.priority = priority;
       this.mute = mute;
       this.offchat = offchat;
       this.privacy = privacy;
       this.settings = settings;
       this.msgTime = msgTime;
       this.msgLength = msgLength;
       this.defaultWallpaper = defaultWallpaper;
       this.wallpaperId = wallpaperId;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public boolean isWooks() {
        return this.wooks;
    }
    
    public void setWooks(boolean wooks) {
        this.wooks = wooks;
    }
    public boolean isRemove() {
        return this.remove;
    }
    
    public void setRemove(boolean remove) {
        this.remove = remove;
    }
    public boolean isBlock() {
        return this.block;
    }
    
    public void setBlock(boolean block) {
        this.block = block;
    }
    public boolean isStarred() {
        return this.starred;
    }
    
    public void setStarred(boolean starred) {
        this.starred = starred;
    }
    public boolean isPriority() {
        return this.priority;
    }
    
    public void setPriority(boolean priority) {
        this.priority = priority;
    }
    public boolean isMute() {
        return this.mute;
    }
    
    public void setMute(boolean mute) {
        this.mute = mute;
    }
    public boolean isOffchat() {
        return this.offchat;
    }
    
    public void setOffchat(boolean offchat) {
        this.offchat = offchat;
    }
    public boolean isPrivacy() {
        return this.privacy;
    }
    
    public void setPrivacy(boolean privacy) {
        this.privacy = privacy;
    }
    public boolean isSettings() {
        return this.settings;
    }
    
    public void setSettings(boolean settings) {
        this.settings = settings;
    }
    public boolean isMsgTime() {
        return this.msgTime;
    }
    
    public void setMsgTime(boolean msgTime) {
        this.msgTime = msgTime;
    }
    public byte getMsgLength() {
        return this.msgLength;
    }
    
    public void setMsgLength(byte msgLength) {
        this.msgLength = msgLength;
    }
    public byte getDefaultWallpaper() {
        return this.defaultWallpaper;
    }
    
    public void setDefaultWallpaper(byte defaultWallpaper) {
        this.defaultWallpaper = defaultWallpaper;
    }
    public String getWallpaperId() {
        return this.wallpaperId;
    }
    
    public void setWallpaperId(String wallpaperId) {
        this.wallpaperId = wallpaperId;
    }




}


