package hibernate.mapping;
// Generated Aug 10, 2018 12:45:26 AM by Hibernate Tools 4.3.1



/**
 * Starredmessages generated by hbm2java
 */
public class Starredmessages  implements java.io.Serializable {


     private long starmsgId;
     private long starredmsgId;
     private long operId;
     private long userId;

    public Starredmessages() {
    }

    public Starredmessages(long starredmsgId, long operId, long userId) {
       this.starredmsgId = starredmsgId;
       this.operId = operId;
       this.userId = userId;
    }
   
    public long getStarmsgId() {
        return this.starmsgId;
    }
    
    public void setStarmsgId(long starmsgId) {
        this.starmsgId = starmsgId;
    }
    public long getStarredmsgId() {
        return this.starredmsgId;
    }
    
    public void setStarredmsgId(long starredmsgId) {
        this.starredmsgId = starredmsgId;
    }
    public long getOperId() {
        return this.operId;
    }
    
    public void setOperId(long operId) {
        this.operId = operId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }




}


