package hibernate.mapping;
// Generated Jul 16, 2018 9:30:26 AM by Hibernate Tools 4.3.1



/**
 * Talkings generated by hbm2java
 */
public class Talkings  implements java.io.Serializable {


     private long autoId;
     private String deviceId;
     private long timestampVal;
     private long timestampTalk;
     private String operId;
     private long userOne;
     private long userTwo;
     private String targetId;
     private String talkingText;
     private boolean replied;
     private boolean edited;
     private boolean deleted;
     private String picId;
     private String origName;
     private String mediaType;
     private Long mediaSize;

    public Talkings() {
    }

	
    public Talkings(String deviceId, long timestampVal, long timestampTalk, String operId, long userOne, long userTwo, String targetId, boolean replied, boolean edited, boolean deleted) {
        this.deviceId = deviceId;
        this.timestampVal = timestampVal;
        this.timestampTalk = timestampTalk;
        this.operId = operId;
        this.userOne = userOne;
        this.userTwo = userTwo;
        this.targetId = targetId;
        this.replied = replied;
        this.edited = edited;
        this.deleted = deleted;
    }
    public Talkings(String deviceId, long timestampVal, long timestampTalk, String operId, long userOne, long userTwo, String targetId, String talkingText, boolean replied, boolean edited, boolean deleted, String picId, String origName, String mediaType, Long mediaSize) {
       this.deviceId = deviceId;
       this.timestampVal = timestampVal;
       this.timestampTalk = timestampTalk;
       this.operId = operId;
       this.userOne = userOne;
       this.userTwo = userTwo;
       this.targetId = targetId;
       this.talkingText = talkingText;
       this.replied = replied;
       this.edited = edited;
       this.deleted = deleted;
       this.picId = picId;
       this.origName = origName;
       this.mediaType = mediaType;
       this.mediaSize = mediaSize;
    }
   
    public long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(long autoId) {
        this.autoId = autoId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getTimestampVal() {
        return this.timestampVal;
    }
    
    public void setTimestampVal(long timestampVal) {
        this.timestampVal = timestampVal;
    }
    public long getTimestampTalk() {
        return this.timestampTalk;
    }
    
    public void setTimestampTalk(long timestampTalk) {
        this.timestampTalk = timestampTalk;
    }
    public String getOperId() {
        return this.operId;
    }
    
    public void setOperId(String operId) {
        this.operId = operId;
    }
    public long getUserOne() {
        return this.userOne;
    }
    
    public void setUserOne(long userOne) {
        this.userOne = userOne;
    }
    public long getUserTwo() {
        return this.userTwo;
    }
    
    public void setUserTwo(long userTwo) {
        this.userTwo = userTwo;
    }
    public String getTargetId() {
        return this.targetId;
    }
    
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }
    public String getTalkingText() {
        return this.talkingText;
    }
    
    public void setTalkingText(String talkingText) {
        this.talkingText = talkingText;
    }
    public boolean isReplied() {
        return this.replied;
    }
    
    public void setReplied(boolean replied) {
        this.replied = replied;
    }
    public boolean isEdited() {
        return this.edited;
    }
    
    public void setEdited(boolean edited) {
        this.edited = edited;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public String getPicId() {
        return this.picId;
    }
    
    public void setPicId(String picId) {
        this.picId = picId;
    }
    public String getOrigName() {
        return this.origName;
    }
    
    public void setOrigName(String origName) {
        this.origName = origName;
    }
    public String getMediaType() {
        return this.mediaType;
    }
    
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }
    public Long getMediaSize() {
        return this.mediaSize;
    }
    
    public void setMediaSize(Long mediaSize) {
        this.mediaSize = mediaSize;
    }




}


