package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Tokens generated by hbm2java
 */
public class Tokens  implements java.io.Serializable {


     private Long tokenId;
     private long userId;
     private String token;
     private boolean isUsed;
     private long setTimestamp;

    public Tokens() {
    }

    public Tokens(long userId, String token, boolean isUsed, long setTimestamp) {
       this.userId = userId;
       this.token = token;
       this.isUsed = isUsed;
       this.setTimestamp = setTimestamp;
    }
   
    public Long getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(Long tokenId) {
        this.tokenId = tokenId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public boolean isIsUsed() {
        return this.isUsed;
    }
    
    public void setIsUsed(boolean isUsed) {
        this.isUsed = isUsed;
    }
    public long getSetTimestamp() {
        return this.setTimestamp;
    }
    
    public void setSetTimestamp(long setTimestamp) {
        this.setTimestamp = setTimestamp;
    }




}


