package hibernate.mapping;
// Generated Aug 21, 2018 4:33:20 PM by Hibernate Tools 4.3.1



/**
 * Userchatlist generated by hbm2java
 */
public class Userchatlist  implements java.io.Serializable {


     private long autoId;
     private long timestampVal;
     private String deviceId;
     private long userOne;
     private long userTwo;
     private long blockedchatOne;
     private long blockedchatTwo;
     private long muteOne;
     private long muteTwo;
     private long offchatOne;
     private long offchatTwo;
     private boolean request;
     private boolean blocked;
     private boolean friend;
     private boolean removed;
     private long sent;
     private long accepted;

    public Userchatlist() {
    }

    public Userchatlist(long timestampVal, String deviceId, long userOne, long userTwo, long blockedchatOne, long blockedchatTwo, long muteOne, long muteTwo, long offchatOne, long offchatTwo, boolean request, boolean blocked, boolean friend, boolean removed, long sent, long accepted) {
       this.timestampVal = timestampVal;
       this.deviceId = deviceId;
       this.userOne = userOne;
       this.userTwo = userTwo;
       this.blockedchatOne = blockedchatOne;
       this.blockedchatTwo = blockedchatTwo;
       this.muteOne = muteOne;
       this.muteTwo = muteTwo;
       this.offchatOne = offchatOne;
       this.offchatTwo = offchatTwo;
       this.request = request;
       this.blocked = blocked;
       this.friend = friend;
       this.removed = removed;
       this.sent = sent;
       this.accepted = accepted;
    }
   
    public long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(long autoId) {
        this.autoId = autoId;
    }
    public long getTimestampVal() {
        return this.timestampVal;
    }
    
    public void setTimestampVal(long timestampVal) {
        this.timestampVal = timestampVal;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getUserOne() {
        return this.userOne;
    }
    
    public void setUserOne(long userOne) {
        this.userOne = userOne;
    }
    public long getUserTwo() {
        return this.userTwo;
    }
    
    public void setUserTwo(long userTwo) {
        this.userTwo = userTwo;
    }
    public long getBlockedchatOne() {
        return this.blockedchatOne;
    }
    
    public void setBlockedchatOne(long blockedchatOne) {
        this.blockedchatOne = blockedchatOne;
    }
    public long getBlockedchatTwo() {
        return this.blockedchatTwo;
    }
    
    public void setBlockedchatTwo(long blockedchatTwo) {
        this.blockedchatTwo = blockedchatTwo;
    }
    public long getMuteOne() {
        return this.muteOne;
    }
    
    public void setMuteOne(long muteOne) {
        this.muteOne = muteOne;
    }
    public long getMuteTwo() {
        return this.muteTwo;
    }
    
    public void setMuteTwo(long muteTwo) {
        this.muteTwo = muteTwo;
    }
    public long getOffchatOne() {
        return this.offchatOne;
    }
    
    public void setOffchatOne(long offchatOne) {
        this.offchatOne = offchatOne;
    }
    public long getOffchatTwo() {
        return this.offchatTwo;
    }
    
    public void setOffchatTwo(long offchatTwo) {
        this.offchatTwo = offchatTwo;
    }
    public boolean isRequest() {
        return this.request;
    }
    
    public void setRequest(boolean request) {
        this.request = request;
    }
    public boolean isBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(boolean blocked) {
        this.blocked = blocked;
    }
    public boolean isFriend() {
        return this.friend;
    }
    
    public void setFriend(boolean friend) {
        this.friend = friend;
    }
    public boolean isRemoved() {
        return this.removed;
    }
    
    public void setRemoved(boolean removed) {
        this.removed = removed;
    }
    public long getSent() {
        return this.sent;
    }
    
    public void setSent(long sent) {
        this.sent = sent;
    }
    public long getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(long accepted) {
        this.accepted = accepted;
    }




}


