package hibernate.mapping;
// Generated Aug 9, 2018 6:16:59 PM by Hibernate Tools 4.3.1



/**
 * Usermessages generated by hbm2java
 */
public class Usermessages  implements java.io.Serializable {


     private long autoId;
     private String deviceId;
     private long operId;
     private long timestampVal;
     private long sender;
     private long receiver;
     private boolean chatRead;
     private boolean chatpageRead;
     private boolean getback;
     private boolean forward;
     private long deletedOne;
     private long deletedTwo;
     private long msgTimestamp;
     private long seenTimestamp;
     private Messages messages;

    public Usermessages() {
    }

	
    public Usermessages(String deviceId, long operId, long timestampVal, long sender, long receiver, boolean chatRead, boolean chatpageRead, boolean getback, boolean forward, long deletedOne, long deletedTwo, long msgTimestamp, long seenTimestamp) {
        this.deviceId = deviceId;
        this.operId = operId;
        this.timestampVal = timestampVal;
        this.sender = sender;
        this.receiver = receiver;
        this.chatRead = chatRead;
        this.chatpageRead = chatpageRead;
        this.getback = getback;
        this.forward = forward;
        this.deletedOne = deletedOne;
        this.deletedTwo = deletedTwo;
        this.msgTimestamp = msgTimestamp;
        this.seenTimestamp = seenTimestamp;
    }
    public Usermessages(String deviceId, long operId, long timestampVal, long sender, long receiver, boolean chatRead, boolean chatpageRead, boolean getback, boolean forward, long deletedOne, long deletedTwo, long msgTimestamp, long seenTimestamp, Messages messages) {
       this.deviceId = deviceId;
       this.operId = operId;
       this.timestampVal = timestampVal;
       this.sender = sender;
       this.receiver = receiver;
       this.chatRead = chatRead;
       this.chatpageRead = chatpageRead;
       this.getback = getback;
       this.forward = forward;
       this.deletedOne = deletedOne;
       this.deletedTwo = deletedTwo;
       this.msgTimestamp = msgTimestamp;
       this.seenTimestamp = seenTimestamp;
       this.messages = messages;
    }
   
    public long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(long autoId) {
        this.autoId = autoId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getOperId() {
        return this.operId;
    }
    
    public void setOperId(long operId) {
        this.operId = operId;
    }
    public long getTimestampVal() {
        return this.timestampVal;
    }
    
    public void setTimestampVal(long timestampVal) {
        this.timestampVal = timestampVal;
    }
    public long getSender() {
        return this.sender;
    }
    
    public void setSender(long sender) {
        this.sender = sender;
    }
    public long getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(long receiver) {
        this.receiver = receiver;
    }
    public boolean isChatRead() {
        return this.chatRead;
    }
    
    public void setChatRead(boolean chatRead) {
        this.chatRead = chatRead;
    }
    public boolean isChatpageRead() {
        return this.chatpageRead;
    }
    
    public void setChatpageRead(boolean chatpageRead) {
        this.chatpageRead = chatpageRead;
    }
    public boolean isGetback() {
        return this.getback;
    }
    
    public void setGetback(boolean getback) {
        this.getback = getback;
    }
    public boolean isForward() {
        return this.forward;
    }
    
    public void setForward(boolean forward) {
        this.forward = forward;
    }
    public long getDeletedOne() {
        return this.deletedOne;
    }
    
    public void setDeletedOne(long deletedOne) {
        this.deletedOne = deletedOne;
    }
    public long getDeletedTwo() {
        return this.deletedTwo;
    }
    
    public void setDeletedTwo(long deletedTwo) {
        this.deletedTwo = deletedTwo;
    }
    public long getMsgTimestamp() {
        return this.msgTimestamp;
    }
    
    public void setMsgTimestamp(long msgTimestamp) {
        this.msgTimestamp = msgTimestamp;
    }
    public long getSeenTimestamp() {
        return this.seenTimestamp;
    }
    
    public void setSeenTimestamp(long seenTimestamp) {
        this.seenTimestamp = seenTimestamp;
    }
    public Messages getMessages() {
        return this.messages;
    }
    
    public void setMessages(Messages messages) {
        this.messages = messages;
    }




}


