package hibernate.mapping;
// Generated Jul 8, 2018 11:27:17 PM by Hibernate Tools 4.3.1



/**
 * Validlogin generated by hbm2java
 */
public class Validlogin  implements java.io.Serializable {


     private String deviceId;
     private long userId;
     private long loginTimestamp;
     private boolean isLogout;
     private String logoutKey;
     private String loginPassword;
     private String loginKey;
     private String loginKeySet;

    public Validlogin() {
    }

    public Validlogin(String deviceId, long userId, long loginTimestamp, boolean isLogout, String logoutKey, String loginPassword, String loginKey, String loginKeySet) {
       this.deviceId = deviceId;
       this.userId = userId;
       this.loginTimestamp = loginTimestamp;
       this.isLogout = isLogout;
       this.logoutKey = logoutKey;
       this.loginPassword = loginPassword;
       this.loginKey = loginKey;
       this.loginKeySet = loginKeySet;
    }
   
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getLoginTimestamp() {
        return this.loginTimestamp;
    }
    
    public void setLoginTimestamp(long loginTimestamp) {
        this.loginTimestamp = loginTimestamp;
    }
    public boolean isIsLogout() {
        return this.isLogout;
    }
    
    public void setIsLogout(boolean isLogout) {
        this.isLogout = isLogout;
    }
    public String getLogoutKey() {
        return this.logoutKey;
    }
    
    public void setLogoutKey(String logoutKey) {
        this.logoutKey = logoutKey;
    }
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    public String getLoginKey() {
        return this.loginKey;
    }
    
    public void setLoginKey(String loginKey) {
        this.loginKey = loginKey;
    }
    public String getLoginKeySet() {
        return this.loginKeySet;
    }
    
    public void setLoginKeySet(String loginKeySet) {
        this.loginKeySet = loginKeySet;
    }




}


